-- SQL statement for create tables
create table links(
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      full_link varchar(200) NOT NULL,
                      expired_at timestamp NOT NULL,
)